# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='agentPicture')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id_fac', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Prop_Category',
            fields=[
                ('id_prop_cat', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Prop_Category',
                'verbose_name_plural': 'Prop_Categories',
            },
        ),
        migrations.CreateModel(
            name='Prop_Facility',
            fields=[
                ('id_prop_fac', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_facilities', to='tospiti.Facility')),
            ],
            options={
                'verbose_name': 'Property_Facility',
                'verbose_name_plural': 'Property_Facilities',
            },
        ),
        migrations.CreateModel(
            name='Prop_Picture',
            fields=[
                ('id_prop_pic', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Prop_Picture')),
            ],
            options={
                'verbose_name': 'Prop_Picture',
                'verbose_name_plural': 'Prop_Pictures',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id_prop', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publised_date', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tospiti.Agent')),
                ('prop_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tospiti.Prop_Category')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.AddField(
            model_name='prop_picture',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='tospiti.Property'),
        ),
        migrations.AddField(
            model_name='prop_facility',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_facilities', to='tospiti.Property'),
        ),
    ]
