# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop_Genre',
            fields=[
                ('id_prop_gen', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='prop_genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tospiti.Prop_Genre'),
            preserve_default=False,
        ),
    ]
