# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0002_auto_20170120_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prop_genre',
            options={'verbose_name': 'Prop_Genre', 'verbose_name_plural': 'Prop_Genres'},
        ),
    ]
