# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0003_auto_20170120_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='squaremeters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
