# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0006_auto_20170127_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tospiti.Agent', verbose_name='Μεσίτης'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Χώροι'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Μπάνια'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Υπνοωμάτια'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Πόλη'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Χώρα'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Σύντομη περιγραφή'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tospiti.Prop_Genre', verbose_name='Προς'),
        ),
        migrations.AlterField(
            model_name='property',
            name='publised_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομινία Δημοσίευσης'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Περιοχή'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Δωμάτια'),
        ),
        migrations.AlterField(
            model_name='property',
            name='squaremeters',
            field=models.IntegerField(blank=True, null=True, verbose_name='Τετραγωνικά'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Τ.Κ.'),
        ),
    ]
