# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0007_auto_20170127_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Κατηγορία', 'verbose_name_plural': 'Κατηγορίες'},
        ),
    ]
