# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0009_auto_20170127_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Μεσίτης', 'verbose_name_plural': 'Μεσίτες'},
        ),
        migrations.AlterModelOptions(
            name='prop_category',
            options={'verbose_name': 'Κατηγορία Ακινήτων', 'verbose_name_plural': 'Κατηγορίες Ακινήτων'},
        ),
        migrations.AlterModelOptions(
            name='prop_facility',
            options={'verbose_name': 'Επιπρόσθετο στοιχείο', 'verbose_name_plural': 'Επιπρόσθετα στοιχεία'},
        ),
        migrations.AlterModelOptions(
            name='prop_genre',
            options={'verbose_name': 'Ακίνητο προς', 'verbose_name_plural': 'Ακίνητα προς'},
        ),
        migrations.AlterModelOptions(
            name='prop_picture',
            options={'verbose_name': 'Εικόνα', 'verbose_name_plural': 'Εικόνες'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Ακίνητο', 'verbose_name_plural': 'Ακίνητα'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(blank=True, choices=[('A', 'Άντρας'), ('Γ', 'Γυναίκα')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Τιμή'),
        ),
    ]
