# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0010_auto_20170127_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Επιπρόσθετο στοιχείο', 'verbose_name_plural': 'Επιπρόσθετα στοιχεία'},
        ),
        migrations.AlterModelOptions(
            name='prop_facility',
            options={'verbose_name': 'Property_Facility', 'verbose_name_plural': 'Property_Facilities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Νομός'),
        ),
    ]
