# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0011_auto_20170128_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Ακίνητο', 'verbose_name_plural': 'Ακίνητα'},
        ),
    ]
