# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0013_auto_20170128_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Μεσίτης', 'verbose_name_plural': 'Μεσίτες'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Επιπρόσθετο στοιχείο', 'verbose_name_plural': 'Επιπρόσθετο στοιχείο'},
        ),
        migrations.AlterModelOptions(
            name='prop_category',
            options={'verbose_name': 'Κατηγορία Ακινήτου', 'verbose_name_plural': 'Κατηγορίες Ακινήτων'},
        ),
        migrations.AlterModelOptions(
            name='prop_genre',
            options={'verbose_name': 'Ακίνητο προς', 'verbose_name_plural': 'Ακίνητα προσ'},
        ),
        migrations.AlterModelOptions(
            name='prop_picture',
            options={'verbose_name': 'Εικόνα', 'verbose_name_plural': 'Εικόνες'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Ακινήτο', 'verbose_name_plural': 'Ακίνητα'},
        ),
    ]
