# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tospiti', '0014_auto_20170128_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Επιπρόσθετο στοιχείο', 'verbose_name_plural': 'Επιπρόσθετα στοιχεία'},
        ),
        migrations.AlterModelOptions(
            name='prop_genre',
            options={'verbose_name': 'Ακίνητο προς', 'verbose_name_plural': 'Ακίνητα προς'},
        ),
    ]
